nav:
  - index.md
  - about.md
  - FFMpeg:
    - ffmpeg/index.md
  - Home Assistant:
    - home-assistant/index.md
    - home-assistant/cloudflare-remote.md
site_url: https://gira0.github.io
site_name: Docs
theme:
  name: material
